const Projects_data=[
    // {id:1,titre:"Hospital Management website",url:"",image:"./images/pr7.png",description:"A website designed for hospital management, facilitating seamless scheduling of patient appointments with doctors. It streamlines hospital operations by efficiently coordinating patient-doctor meetings.",languages:["Html","CSS(Bootstrap)","Javascript(Jquery)","Mysql","Php"]},
    {id:3,titre:"Your Multilingual Coaching Hub",url:"",image:"./images/pr9.png",description:"During my internship, I developed Sportify, a sports coaching platform offering personalized programs for various disciplines. I created a secure, intuitive user interface that provides expert advice and supports an active community, catering to users in Arabic-speaking countries and beyond",languages:["Html","CSS (Tailwind)","Javascript (React js)","Mysql","Php (Laravel)","Use Api"]},
    {id:7,titre:" Administrative Management System for ENS Tétouan  ",url:"https://github.com/ayoub-Ouba/Administrative-Management-System-for-ENS-T-touan.git",image:"./images/pr10.png",description:"I developed a project assigned by my department head for the École Normale Supérieure de Tétouan, enabling administrators to securely log in and manage student records, departments, and academic programs. The system includes user authentication to ensure only authorized personnel can access and update information",languages:["Html","CSS (Tailwind)","Javascript (React js)","Mysql","JAVA (JEE)","Use Api"]},
    {id:5,titre:"Microservices Management website",url:"https://github.com/Oubida-Mohamed/PFE-ReactApp",image:"./images/pr8.png",description:"A website similar to Fiverr, efficiently coordinating microservices for sellers and buyers to streamline transactions. By providing a seamless management platform, it fosters a dynamic marketplace for diverse services.",languages:["Html","CSS (Tailwind)","Javascript (React js)","Mysql","Php (Laravel)","Use Api"]},
    {id:2,titre:"E-commerce",url:"https://github.com/ayoub-Ouba/E-commerce-Ru",image:"./images/pr1.png",description:"An intuitive e-commerce platform created for smooth product browsing, secure checkout, and easy cart management. It enhances user experience with efficient search and filtering options, making online shopping straightforward and enjoyable ",languages:["Html","CSS(Bootstrap)","Javascript (React js)"]},
    {id:4,titre:"Patisserie Management",url:"",image:"./images/pr3.png",description:"Complete development of a web management site for Pâtisserie CHAUQUETE as part of an internship. The project involved designing and implementing features to manage inventory, track product inflows and outflows, and handle point-of-sale operations efficiently. ",languages:["Html","CSS (Tailwind)","Javascript (React js)","Javascript (Express js)","Use Api"]},
    {id:6,titre:"Users Management desktop App",url:"https://github.com/ayoub-Ouba/Users-Management-desktop-App.git",image:"./images/pr6.png",description:"This desktop app streamlines user management, enabling easy addition, modification, and deletion of user information. Its user-friendly interface ensures quick navigation, boosting usability and productivity.",languages:["Python","Tkinter","MongoDB"]},

]
export {Projects_data}